<%-- 
    Document   : descrizione
    Created on : 15-Jul-2017, 17:51:05
    Author     : D_con
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>

<html>
    <head>
        <title>Descrizione</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Davide Contini">
        <meta name="keywords" content="cerca nerdbook social nerd info descrizione">
        <link rel="stylesheet" type="text/css" href="style.css" media="screen">
    </head>
    
    
    <body>
        
        <header>
            
            <div id="DescTitle">
                
                <h1>Nerdbook</h1>
            
            </div>
            
            
        </header>
        
        <nav>
            <ul>
                <li><a href="login.html">Login</a></li>
            </ul>
        </nav>
        
        <div id="DescInfo">
         
            <h1>Descrizione Nerdbook</h1>
            
            <h2>Link interni:</h2>
            <ol>
                <li><a href="#InfoNerd">Cosa &egrave; nerdbook?</a></li>
                <li><a href="#IscrizNerd">Come iscriversi</a></li>
                <li><a href="#PagaNerd">Modalità di pagamento</a></li>
                
            </ol>
            
            <h3 id="InfoNerd">Che cosa &egrave; nerdbook?</h3>
            <p>
                Nerdbook è un social network totalmente gratis in cui poter trovare nerd sociofobici come te che non sono in grado di rivolgere più di due parole ad una persona senza collassare a terra, qua potrai avere tutti gli amici che vuoi e non doverne mai incontrare nessuno (che è la parte migliore), quindi basta essere emarginati per colpa di una stupida fobia del contatto fisico con individui della tua stessa specie! Iscriviti a Nerdbook :D
                Jason Voorhees is the main character from the Friday the 13th series. He first appeared in Friday the 13th (1980) as the young son of camp cook-turned-murderer Mrs. Voorhees, in which he was portrayed by Ari Lehman. Created by Victor Miller, with contributions by Ron Kurz, Sean S. Cunningham, and Tom Savini, Jason was not originally intended to carry the series as the main antagonist. The character has subsequently been represented in various other media, including novels, video games, comic books, and a cross-over film with another iconic horror film character, Freddy Krueger.
                The character has primarily been an antagonist in the films, whether by stalking and killing the other characters, or acting as a psychological threat to the protagonist, as is the case in Friday the 13th: A New Beginning. Since Lehman's portrayal, the character has been represented by numerous actors and stuntmen, sometimes by more than one at a time; this has caused some controversy as to who should receive credit for the portrayal. Kane Hodder is the best known of the stuntmen to portray Jason Voorhees, having played the character in four consecutive films.[3][4]
                The character's physical appearance has gone through many transformations, with various special makeup effects artists making their mark on the character's design, including makeup artist Stan Winston. Tom Savini's initial design has been the basis for many of the later incarnations. The trademark hockey goalie mask did not appear until Friday the 13th Part III. Since Friday the 13th Part VI: Jason Lives, filmmakers have given Jason superhuman strength, regenerative powers, and near invulnerability. He has been seen as a sympathetic character, whose motivation for killing has been cited as being driven by the immoral actions of his victims and his own rage over having drowned as a child.[5] Jason Voorhees has been featured in various humor magazines, referenced in feature films, parodied in television shows, and was the inspiration for a horror punk band. Several toy lines have been released based on various versions of the character from the Friday the 13th films. Jason Voorhees's hockey mask is a widely recognized image in popular culture
                In his original appearance, Jason was scripted as a mentally disabled young boy.[90] Since Friday the 13th, Jason Voorhees has been depicted as a non-verbal, indestructible, machete-wielding mass murderer.[91][92] Jason is primarily portrayed as being completely silent throughout the film series. Exceptions to this include flashbacks of Jason as a child, and a brief scene in Jason Takes Manhattan where the character cries out "Mommy, please don't let me drown!" in a child's voice before being submerged in toxic waste, and in Jason Goes To Hell where his spirit possesses other individuals.[57] Online magazine Salon's Andrew O'Hehir describes Jason as a "silent, expressionless...blank slate."[93] When discussing Jason psychologically, Sean S. Cunningham said, "...he doesn't have any personality. He's like a great white shark. You can't really defeat him. All you can hope for is to survive."[94] Since Friday the 13th Part VI: Jason Lives, Jason has been a "virtually indestructible" being. Tom McLoughlin, the film's director, felt it was silly that Jason had previously been just another guy in a mask, who would kill people left and right, but get "beaten up and knocked down by the heroine at the end". McLoughlin wanted Jason to be more of a "formidable, unstoppable monster".[25] In resurrecting Jason from the dead, McLoughlin also gave him the weakness of being rendered helpless if trapped beneath the waters of Crystal Lake; inspired by vampire lore, McLoughlin decided that Jason had in fact drowned as a child, and that returning him to his original resting place would immobilize him.[95] This weakness would be presented again in The New Blood, and the idea that Jason had drowned as a child was taken up by director Rob Hedden as a plot element in Jason Takes Manhattan.[57]
                Many have given suggestions as Jason's motivation for killing. Ken Kirzinger refers to Jason as a "psychotic mama's boy gone horribly awry...very resilient. You can't kill him, but he feels pain, just not like everyone else."[96] Kirzinger goes on to say that Jason is a "psycho-savant", and believes his actions are based on pleasing his mother, and not anything personal.[79] Andrew O'Hehir has stated, "Coursing hormones act, of course, as smelling salts to prudish Jason, that ever-vigilant enforcer of William Bennett-style values."[93] Todd Farmer, writer for Jason X, wrote the scene where Jason wakes from cryonic hibernation just as two of the teenagers are having sex. Farmer liked the idea that sex acts triggered Jason back to life.[78] Whatever his motivations, Kane Hodder believes there is a limit to what he will do. According to Hodder, Jason might violently murder any person he comes across, but when Jason Takes Manhattan called for Hodder to kick the lead character's dog, Hodder refused, stating that, while Jason has no qualms against killing humans, he is not bad enough to hurt animals.[97] Another example from Jason Takes Manhattan, involves Jason being confronted by a street gang of young teenage boys one of whom threatens him with a knife, however Jason chooses not to kill them and instead scares them off by lifting up his mask and showing them his face. Likewise, director Tom McLoughlin chose not to have Jason harm any of the children he encounters in Jason Lives, stating that Jason would not kill a child, out of a sympathy for the plight of children generated by his own death as a child.[95]
                In an early draft of Freddy vs. Jason, it was decided that one of the villains needed a redeemable factor. Ronald D. Moore, co-writer of the first draft, explained that Jason was the easiest to make redeemable, because no one had previously ventured into the psychology surrounding the character. Moore saw the character as a "blank slate", and felt he was a character the audience could really root for.[98] Another draft, penned by Mark Protosevich, followed Moore's idea of Jason having a redeemable quality. In the draft, Jason protects a pregnant teenager named Rachel Daniels. Protosevich explained, "It gets into this whole idea of there being two kinds of monsters. Freddy is a figure of actual pure evil and Jason is more like a figure of vengeance who punishes people he feels do not deserve to live. Ultimately, the two of them clash and Jason becomes an honorable monster."[98] Writers Damian Shannon and Mark Swift, who wrote the final draft of the film, disagreed about making Jason a hero, although they drew comparisons between the fact that Freddy was a victimizer and Jason was a victim. They stated, "We did not want to make Jason any less scary. He's still a brutal killer ... We never wanted to put them in a situation where Jason is a hero ... They're both villains to be equally feared."[98] Brenna O'Brien, co-founder of Fridaythe13thfilms.com, saw the character as having sympathetic qualities. She stated, "[Jason] was a deformed child who almost drowned and then spent the rest of his childhood growing up alone in the woods. He saw his mother get murdered by a camp counselor in the first Friday the 13th, and so now he exacts his revenge on anyone who returns to Camp Crystal Lake. Teenage fans can identify with that sense of rejection and isolation, which you can't really get from other killers like Freddy Krueger and Michael Myers."[6]
                As Jason went through some characterization changes in the 2009 film, Derek Mears likens him more to a combination of John Rambo, Tarzan, and the Abominable Snowman from Looney Tunes. To him, this Jason is similar to Rambo because he sets up the other characters to fall into his traps. Like Rambo, he is more calculated because he feels that he has been wronged and he is fighting back; he is meant to be more sympathetic in this film.[99] Fuller and Form contend that they did not want to make Jason too sympathetic to the audience. As Brad Fuller explains, "We do not want him to be sympathetic. Jason is not a comedic character, he is not sympathetic. He's a killing machine. Plain and simple."[100]
                In 2005, California State University's Media Psychology Lab surveyed 1,166 people Americans aged from 16 to 91 on the psychological appeal of movie monsters. Many of the characteristics associated with Jason Voorhees were appealing to the participants. In the survey, Jason was considered to be an "unstoppable killing machine." Participants were impressed by the "cornucopic feats of slicing and dicing a seemingly endless number of adolescents and the occasional adult." Out of the ten monsters used in the survey—which included vampires, Freddy Krueger, Frankenstein's monster, Michael Myers, Godzilla, Chucky, Hannibal Lecter, King Kong, and the Alien—Jason scored the highest in all the categories involving killing variables. Further characteristics that appealed to the participants included Jason's "immortality, his apparent enjoyment of killing [and] his superhuman strength."[101]
            </p>
            
            <h3 id="IscrizNerd">Come iscriversi?</h3>
            <p>
                Iscriversi è molto semplice, inserisci nome utente(usa il tuo nome vero non roba come D3atHKilL3r93 perchè verrai bannato in tempo zero) una password e le credenziali della tua carta di credito nel box di testo apposito. 
                Frederick Charles "Freddy" Krueger is a character of the A Nightmare on Elm Street film series. He first appeared in Wes Craven's A Nightmare on Elm Street (1984) as a burnt serial killer who uses a glove armed with razors to kill his victims in their dreams, causing their deaths in the real world as well. In the dream world, he is a powerful force and almost completely invulnerable to damage. However, whenever Freddy is pulled into the real world, he has normal human vulnerabilities. Krueger was created by Wes Craven, and had been consistently portrayed by Robert Englund since his first appearance. In the 2010 franchise reboot, he was portrayed by Jackie Earle Haley. In 2011, Freddy appeared as a playable character in the video game Mortal Kombat.[2] Over the course of the series, Freddy has battled numerous survivors including Nancy Thompson.[3]
                In the Nightmares on Elm Street comics, Freddy partners up with Devonne, also known as The Springwood Killer.[4] Freddy is a nightmare-demon who attacks his victims from within their dreams. He is commonly identified by his burned, disfigured face, red-and-green striped sweater, brown fedora, and trademark metal-clawed brown leather glove only on his right hand. This glove was the product of Krueger's own imagination, the blade having been welded by himself. Robert Englund has said many times that he feels the character represents neglect, particularly that suffered by children. The character also more broadly represents subconscious fears.
                Wizard magazine rated Freddy the 14th greatest villain,[5] the British television channel Sky2 listed him 8th,[6] and the American Film Institute ranked him 40th on its "AFI's 100 Years... 100 Heroes and Villains" list.[7] In 2010, Freddy won an award for Best Villain (formerly Most Vile Villain) at the Scream Awards.
                Wes Craven said his inspiration for the basis of Freddy Krueger's power stemmed from several stories in the Los Angeles Times about a series of mysterious deaths: All the victims had reported recurring nightmares and died in their sleep.[14] Additionally, Craven's original script characterized Freddy as a child molester, which Craven said was the "worst thing" he could think of. The decision was made to instead make him a child murderer in order to avoid being accused of exploiting the spate of highly publicized child molestation cases in California around the time A Nightmare on Elm Street went into production.[15] Craven's inspirations for the character included a bully from his school during his youth, a disfigured homeless man who had frightened him when he was 11, and the 1970s pop song "Dream Weaver" by Gary Wright. In an interview, he said, "When I looked down there was a man very much like Freddy walking along the sidewalk. He must have sensed that someone was looking at him and stopped and looked right into my face. He scared the living daylights out of me, so I jumped back into the shadows. I waited and waited to hear him walk away. Finally I thought he must have gone, so I stepped back to the window. The guy was not only still looking at me but he thrust his head forward as if to say, 'Yes, I'm still looking at you.' The man walked towards the apartment building's entrance. I ran through the apartment to our front door as he was walking into our building on the lower floor. I heard him starting up the stairs. My brother, who is ten years older than me, got a baseball bat and went out to the corridor but he was gone."[16]
                Freddy's back story is revealed gradually throughout the series. In A Nightmare on Elm Street 3: Dream Warriors, the protagonists learn that Freddy's mother, Amanda Krueger, was a nun who worked in Westin Hills mental hospital caring for the inmates. Freddy was conceived when she was accidentally locked inside over the Christmas holiday and gang-raped by a group of the inmates, thus making him "the bastard son of 100 maniacs". Freddy's Dead: The Final Nightmare depicts Freddy's traumatic childhood; he displayed sociopathic behavior at a young age and was often teased by classmates. He was adopted as a child by an abusive alcoholic named Mr. Underwood, who teaches him how to torture animals and inflict pain on himself. Freddy eventually murders him, with no apparent consequences, and becomes a serial killer. The film also reveals that when Freddy reached adulthood, he married a woman named Loretta, with whom he fathered a daughter named Katherine. After the birth of his daughter, he tried to lead a normal life, but his murderous nature eventually overcame him, and he murdered 20 children on Elm Street between 1963 and 1966. He later murdered his wife after she discovered the evidence of his child killings, which Katherine witnessed. She told the authorities and Freddy was arrested for the murder of his wife and the Elm Street children. In 1968, he was put on trial, but released on a technicality, leading to his death at the hands of the parents of his victims. In his dying moments, the Dream Demons came to him to offer him immortality in exchange for being their agent, which Freddy accepted. His daughter, Katherine, was later moved out of Springwood, adopted, and renamed Maggie Burroughs.
                In Wes Craven's New Nightmare, Freddy is characterized as a symbol of something powerful and ancient, and is given more stature and muscles.[17] Unlike the six movies before it, New Nightmare shows Freddy as closer to what Wes Craven originally intended, toning down his comedic side while strengthening the more menacing aspects of his character.
                Throughout the series, Freddy's potential victims often experience dreams of young children, jumping rope and chanting a rhyme to the tune of "One, Two, Buckle My Shoe" with the lyrics changed to "One, Two, Freddy's coming for you", often as an omen to Freddy's presence or a precursor to his attacks.
                In the 2010 remake of A Nightmare On Elm Street, Jackie Earle Haley portrayed Freddy Krueger. In the film, Krueger is depicted as a child abuser who worked as a gardener at a local preschool.
                Freddy Krueger's physical appearance has remained largely consistent throughout the film series, although minor changes were made in subsequent films. He wears a striped red-and-green sweater (solid red sleeves in the original film), a dark brown fedora, his bladed glove, loose black trousers (brown in the original film), and worn working boots, in keeping with his blue collar background. His skin is scarred and burned as a result of being burned alive by the parents of Springwood, and he has no hair at all on his head as it presumably all burned off. In the original film, only Freddy's face was burned, while the scars have spread to the rest of his body from the second film onwards. His blood is occasionally a dark, oily color, or greenish in hue when he is in the Dreamworld. In the original film, Freddy remains in the shadows and under lower light much longer than he does in the later pictures. In the second film, there are some scenes where Freddy is shown without his glove, and instead with the blades protruding from the tips of his fingers. As the films began to emphasize the comedic, wise-cracking aspect of the character, he began to don various costumes and take on other forms, such as dressing as a waiter or wearing a Superman inspired version of his sweater with a cape (The Dream Child), appearing as a video game sprite (Freddy's Dead), a giant snake-like creature (Dream Warriors), and a Hookah smoking caterpillar (Freddy vs. Jason).
                In New Nightmare, Freddy's appearance is updated considerably, giving him a green fedora that matched his sweater stripes, skin-tight leather pants, knee-high black boots, a turtleneck version of his trademark sweater, a dark blue trench coat, and a fifth claw on his glove, which also has a far more organic appearance, resembling the exposed muscle tissue of an actual hand. Freddy also has fewer burns on his face, though these are more severe, with his muscle tissue exposed in numerous places. Compared to his other incarnations, this Freddy's injuries are more like those of an actual burn victim. For the 2010 remake, Freddy is returned to his iconic attire, but the burns on his face are intensified with further bleaching of the skin and exposed facial tissue on the left cheek, reminiscent of actual third degree burns.
                Wes Craven claimed that part of the inspiration for Freddy's infamous glove was from his cat, as he watched it claw the side of his couch one night.[18]
                In an interview he said, "Part of it was an objective goal to make the character memorable, since it seems that every character that has been successful has had some kind of unique weapon, whether it be a chain saw or a machete, etc. I was also looking for a primal fear which is embedded in the subconscious of people of all cultures. One of those is the fear of teeth being broken, which I used in my first film. Another is the claw of an animal, like a saber-toothed tiger reaching with its tremendous hooks. I transposed this into a human hand. The original script had the blades being fishing knives."[19]
                When Jim Doyle, the creator of Freddy's claw, asked Craven what he wanted, Craven responded, "It's kind of like really long fingernails, I want the glove to look like something that someone could make who has the skills of a boilermaker."[18] Doyle explained, "Then we hunted around for knives. We picked out this bizarre-looking steak knife, we thought that this looked really cool, we thought it would look even cooler if we turned it over and used it upside down. We had to remove the back edge and put another edge on it, because we were actually using the knife upside down." Later Doyle had three duplicates of the glove made, two of which were used as stunt gloves in long shots.[18]
                For New Nightmare, Lou Carlucci, the effects coordinator, remodeled Freddy's glove for a more "organic look". He says, "I did the original glove on the first Nightmare and we deliberately made that rough and primitive looking, like something that would be constructed in somebody's home workshop. Since this is supposed to be a new look for Freddy, Craven and everybody involved decided that the glove should be different. This hand has more muscle and bone texture to it, the blades are shinier and in one case, are retractable. Everything about this glove has a much cleaner look to it, it's more a natural part of his hand than a glove." The new glove has five claws.[citation needed]
                In the 2010 remake, the glove is redesigned as a metal gauntlet with four finger bars, but it is patterned after its original design.
                Freddy's glove appeared in the 1987 horror-comedy Evil Dead II: Dead by Dawn above the door on the inside of a toolshed. This was Sam Raimi's response to Wes Craven showing footage of The Evil Dead in A Nightmare on Elm Street, which in turn was a response to Sam Raimi putting a poster of Craven's 1977 film The Hills Have Eyes in The Evil Dead.[citation needed] The glove also appears in the 1998 horror-comedy Bride of Chucky in an evidence locker room that also contains the remains of the film's villain Chucky, the chainsaw of Leatherface from The Texas Chainsaw Massacre, and the masks of Michael Myers from Halloween and Jason Voorhees from Friday the 13th.
                At the end of the movie Jason Goes To Hell: The Final Friday, the mask of the title character, Jason Voorhees, played by Kane Hodder, is dragged under the earth by Freddy's gloved hand, thus setting up Freddy vs. Jason. Freddy's gloved hand, in the ending, was played by Kane Hodder.[20]
            </p>
            
            <h3 id="PagaNerd">Nerdbook &egrave; gratis o a pagamento?</h3>
            <p>
                Iscriversi a NErdbook &egrave; gratis ma i post che conterranno frasi come un mi piace una preghiera dovranno essere pagati. Michael Myers is a fictional character from the Halloween series of slasher films. He first appears in John Carpenter's Halloween (1978) as a young boy who murders his older sister, then fifteen years later returns home to murder more teenagers. In the original Halloween, the adult Michael Myers, referred to as The Shape in the closing credits, was portrayed by Nick Castle for most of the film, with Tony Moran and Tommy Lee Wallace substituting in during the final scenes. The character was created by Debra Hill and John Carpenter and has appeared in nine films, as well as novels, multiple video games, and several comic books.
                The character is the primary antagonist in the Halloween film series, except Halloween III: Season of the Witch, which is not connected in continuity to the rest of the films. Since Castle, Moran, and Wallace put on the mask in the original film, six people have stepped into the role. Tyler Mane is the only actor to have portrayed Michael Myers in consecutive films, and one of only two actors to portray the character more than once. Michael Myers is characterized as pure evil, both directly in the films, by the filmmakers who created and developed the character over nine films, as well as by random participants in a survey.[2][3]
                A common characterization is that Michael Myers is evil. John Carpenter has described the character as "almost a supernatural force - a force of nature. An evil force that's loose," a force that is "unkillable".[2] Professor Nicholas Rogers elaborates, "Myers is depicted as a mythic, elusive bogeyman, one of superhuman strength who cannot be killed by bullets, stab wounds, or fire."[29] Carpenter's inspiration for the "evil" that Michael would embody came when he was in college. While on a class trip at a mental institution in Kentucky, Carpenter visited "the most serious, mentally ill patients". Among those patients was a young boy around twelve to thirteen years-old. The boy gave this "schizophrenic stare", "a real evil stare", which Carpenter found "unsettling", "creepy", and "completely insane". Carpenter's experience would inspire the characterization that Loomis would give of Michael to Sheriff Brackett in the original film. Debra Hill has stated the scene where Michael kills the Wallaces' German Shepherd was done to illustrate how he is "really evil and deadly".[28]
                The ending scene of Michael being shot six times, and then disappearing from the ground outside the house, was meant to terrify the imagination of the audience. Carpenter tried to keep the audience guessing as to who Michael Myers really is—he is gone, and everywhere at the same time; he is more than human; he may be supernatural, and no one knows how he got that way. To Carpenter, keeping the audience guessing was better than explaining away the character with "he's cursed by some..."[28] For Josh Hartnett, who portrayed John Tate in Halloween H20, "it's that abstract, it's easier for me to be afraid of it. You know, someone who just kind of appears and, you know [mimics stabbing noise from Psycho] instead of an actual human who you think you can talk to. And no remorse, it's got no feelings, that's the most frightening, definitely." Richard Schickel, film critic for TIME, felt Michael was "irrational" and "really angry about something", having what Schickel referred to as "a kind of primitive, obsessed intelligence". Schickel considered this the "definition of a good monster", by making the character appear "less than human", but having enough intelligence "to be dangerous".[2]
                "Michael Myers is enduring because he's pure evil."
                —Steve Miner[2]
                Dominique Othenin-Girard attempted to have audiences "relate to 'Evil', to Michael Myers's 'ill' side". Girard wanted Michael to appear "more human [...] even vulnerable, with contradicting feelings inside of him". He illustrated these feelings with a scene where Michael removes his mask and sheds a tear. Girard explains, "Again, to humanize him, to give him a tear. If Evil or in this case our boogeyman knows pain, or love or demonstrate a feeling of regrets; he becomes even more scary to me if he pursues his malefic action. He shows an evil determination beyond his feelings. Dr. Loomis tries to reach his emotional side several times in [Halloween 5]. He thinks he could cure Michael through his feelings."[30]
                Daniel Farrands, writer of The Curse of Michael Myers, describes the character as a "sexual deviant". According to him, the way Michael follows girls around and watches them contains a subtext of repressed sexuality. Farrands theorizes that, as a child, Michael became fixated on the murder of his sister Judith, and for his own twisted reasons felt the need to repeat that action over and over again, finding a sister-like figure in Laurie who excited him sexually. He also believes that by making Laurie, Michael's literal sister, the sequels took away from the simplicity and relatability of the original Halloween. Nevertheless, when writing Curse, Farrands was tasked with creating a mythology for Michael which defined his motives and why he could not be killed. He says, "He can't just be a man anymore, he's gone beyond that. He's mythical. He's supernatural. So, I took it from that standpoint that there's something else driving him. A force that goes beyond that five senses that has infected this boy's soul and now is driving him." As the script developed and more people became involved, Farrands admits that the film went too far in explaining Michael Myers and that he himself was not completely satisfied with the finished product.[31]
                Michael does not speak in the films; the first time audiences ever hear his voice is in the 2007 Rob Zombie reboot. Michael speaks as a child during the beginning of the film, but while in Smith's Grove he stops talking completely. Rob Zombie originally planned to have the adult Michael speak to Laurie in the film's finale, simply saying his childhood nickname for her, "Boo". Zombie explained that this version was not used because he was afraid having the character talk at that point would demystify him too much, and because the act of Michael handing Laurie the photograph of them together was enough.[32]
                Describing aspects of Michael Myers which he wanted to explore in the comic book Halloween: Nightdance, writer Stefan Hutchinson mentions the character's "bizarre and dark sense of humor", as seen when he wore a sheet over his head to trick a girl into thinking he was her boyfriend, and the satisfaction he gets from scaring the characters before he murders them, such as letting Laurie know he is stalking her. Hutchinson feels there is a perverse nature to Michael's actions: "see the difference between how he watches and pursues women to men".[25] He also suggests that Michael Myers' hometown of Haddonfield is the cause of his behavior, likening his situation to that of Jack the Ripper, citing Myers as a "product of normal surburbia - all the repressed emotion of fake Norman Rockwell smiles". Hutchinson describes Michael as a "monster of abjection". When asked his opinion of Rob Zombie's expansion on Michael's family life, Hutchinson says that explaining why Michael does what he does "[reduces] the character". That being said, Hutchinson explores the nature of evil in the short story Charlie—included in the Halloween Nightdance trade paperback—and says that Michael Myers spent fifteen years "attuning himself to this force to the point where he is, as Loomis says, 'pure evil'".[33] Nightdance artist Tim Seeley describes the character's personality in John Carpenter's 1978 film as "a void", which allows the character to be more open to interpretation than the later sequels allowed him. He surmises that Michael embodies a part of everyone; a part people are afraid will one day "snap and knife someone", which lends to the fear that Michael creates on screen.[25]
                In 2005, a study was conducted by the Media Psychology Lab of California State University, Los Angeles on the psychological appeal of movie monsters—vampires, Freddy Krueger, Frankenstein's monster, Jason Voorhees, Godzilla, Chucky, Hannibal Lecter, King Kong, the Alien, and the shark from Jaws—which surveyed 1,166 people nationwide (United States), with ages ranging from 16 to 91. It was published in the Journal of Media Psychology. In the survey, Michael was considered to be the "embodiment of pure evil"; when compared to the other characters, Michael Myers was rated the highest. Michael was characterized lending to the understanding of insanity, being ranked second to Hannibal Lecter in this category; he also placed first as the character who shows audiences the "dark side of human nature". He was rated second in the category "monster enjoys killing" by the participants, and believed to have "superhuman strength". Michael was rated highest among the characters in the "monster is an outcast" category.[3]7



                
            </p>
           
        </div>
        
        
    </body>
    
    
</html>
